[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "enexlib"
version = "0.1.1"
description = "Convert Evernote export files to plaintext."
keywords = ["evernote", "enex"]
requires-python = ">=3"
dependencies = [
    "beautifulsoup4>=4.12.2",
    "lxml>=4.9.3",
    "soupsieve>=2.5",
]
readme = "README.md"

[project.urls]
"Source" = "https://github.com/whitgroves/enexlib"