name: Run Tests

run-name: Tests -- ${{ github.sha }}

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Pytest
        run: pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: test
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Pylint
        run: pylint enexlib/* test_enexlib.py

  pull-request:
    name: Create PR
    runs-on: ubuntu-latest
    environment: test
    needs: [test, lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BODY: Created by GitHub action (run-tests.yml).
          PR_NAME: Merge ${{ github.ref_name }} -> master
        run: gh pr edit ${{ github.ref_name }} -b '${{ env.PR_BODY }}' -t '${{ env.PR_NAME }}' && gh pr reopen ${{ github.ref_name }} || gh pr create -B master -H ${{ github.ref_name }} -t '${{ env.PR_NAME }}' -b '${{ env.PR_BODY }}'